name: Deploy SNAPSHOT

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    uses: eabadillom/github-actions/.github/workflows/maven-publish.yml@main
    with:
      publish-type: snapshot
      github-username: ${{ github.repository_owner }}
      java-version: "8"

