name: Deploy SNAPSHOT

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    uses: TU_USUARIO/github-actions/.github/workflows/maven-publish.yml@main
    with:
      publish-type: snapshot
      github-username: eabadillom
      java-version: "8"

